export default [
  {
    id: 0,
    name: "Fulling",
    description: "AI-powered Full-stack Engineer Agent. Generates 100% AI-written code for full-stack applications.",
    image: "images/projects/fulling.png",
    tags: ["React", "TypeScript", "NextJS", "PostgreSQL", "Prisma", "AI-Agent", "LLM"],
    liveview: "https://fulling.ai/",
    github: "https://github.com/trendsw/fulling",
    alt: "AI-powered Full-stack Engineer Agent",
  },
  {
    id: 1,
    name: "Infinitunes",
    description: "Music Player Web App",
    image: "images/projects/infinitunes.png",
    tags: ["NextJS", "Music-Streaming", "Next-Auth", "Drizzle", "TailwindCSS"],
    liveview: "https://infinitunes.rajputhemant.dev/",
    github: "https://github.com/trendsw/infinitunes",
    alt: "Music Player Web App",
  },
  {
    id: 2,
    name: "Color Museum",
    description: "NFT marketplace for color NFTs",
    image: "images/projects/nft-marketplace.jpg",
    tags: ["NextJS", "ExpressJS", "Blockchain", "PostgreSQL", "Bootstrap"],
    liveview: "https://color.museum",
    github: "/",
    alt: "Ethereum based NFT marketplace project",
  },
  {
    id: 3,
    name: "Iswap",
    description: "CEX site base on Tron Net",
    image: "images/projects/iswap.jpg",
    tags: ["React", "ExpressJS", "Blockchain", "MySQL","Bootstrap"],
    liveview: "https://intercroneswap.com/#/",
    github: "/",
    alt: "CEX site base on Tron",
  },
  {
    id: 4,
    name: "Shadboard",
    description: "Open-Source Admin Dashboard Template",
    image: "images/projects/shadboard.png",
    tags: ["React", "Radix-UI", "ShadCN", "TailwindCSS"],
    liveview: "https://shadboard.vercel.app/",
    github: "https://github.com/trendsw/shadboard",
    alt: "Open-Source Admin Dashboard Template",
  },
  {
    id: 5,
    name: "AimFina",
    description: "Financial AI",
    image: "images/projects/aimfina.png",
    tags: ["React", "NextJS", "Django", "TailwindCSS", "PostgreSQL", "Stripe", "LLM", "Firebase"],
    liveview: "https://aimfina.com/",
    github: "/",
    alt: "This is the financial AI stie",
  },
  {
    id: 6,
    name: "One Model Place",
    description: "This is the fashon model site",
    image: "images/projects/fashon-model.jpg",
    tags: ["React", "Laravel", "TailwindCSS", "MySQL"],
    liveview: "https://www.onemodelplace.com/",
    github: "/",
    alt: "Popular model site",
  },
  {
    id: 7,
    name: "Stablo",
    description: "Blog Website Platform",
    image: "images/projects/stablo.png",
    tags: ["React", "NextJS", "TailwindCSS", "SanityCMS"],
    liveview: "https://stablo.web3templates.com/",
    github: "https://github.com/trendsw/stablo",
    alt: "Blog Website Platform",
  },
  {
    id: 8,
    name: "Chewy",
    description: "Online shopping site for buying various animal foods",
    image: "images/projects/chewy.jpg",
    tags: ["React", "Laravel", "Bootstrap", "MongoDB"],
    liveview: "https://www.chewy.com/",
    github: "/",
    alt: "Online animal food shop",
  },
  {
    id: 9,
    name: "Travel Planner",
    description: "AI travel planner",
    image: "images/projects/travel-planner-ai.png",
    tags: ["React", "NextJS", "OpenAI", "Resend", "Convex", "TailwindCSS", "Clerk"],
    liveview: "https://travelplannerai.site/",
    github: "https://github.com/trendsw/travel-planner-ai",
    alt: "AI travel planner",
  },
];
