export default {
  PostgreSQL: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">PostgreSQL</div>`,
  Resend: `<div class="work-item-tag" style="background: #21BAEB;">Resend</div>`,
  MongoDB: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">MongoDB</div>`,
  OpenAI: `<div class="work-item-tag" style="background: #000000;">OpenAI</div>`,
  MySQL: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">MySQL</div>`,
  SanityCMS: `<div class="work-item-tag" style="background: #FFB800;">SanityCMS</div>`,
  'Next-Auth': `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">Next-Auth</div>`,
  React: `<div class="work-item-tag" style="background: #FFB800;">React</div>`,
  Drizzle: `<div class="work-item-tag" style="background: #FFB800;">Drizzle</div>`,
  NextJS: `<div class="work-item-tag" style="background: #000000;">NextJS</div>`,
  VueJS: `<div class="work-item-tag" style="background: #FFB800;">VueJS</div>`,
  Bootstrap: `<div class="work-item-tag" style="background: #000000;">Bootstrap</div>`,
  NuxtJS: `<div class="work-item-tag" style="background: #FFB800;">NuxtJS</div>`,
  ExpressJS: `<div class="work-item-tag" style="background: #5A69EC;">ExpressJS</div>`,
  ShadCN: `<div class="work-item-tag" style="background: #FFB800;">ShadCN</div>`,
  Stripe: `<div class="work-item-tag" style="background: #5A69EC;">Stripe</div>`,
  'Radix-UI': `<div class="work-item-tag" style="background: #21BAEB;">Radix-UI</div>`,
  Django: `<div class="work-item-tag" style="background: #5A69FF;">Django</div>`,
  LLM: `<div class="work-item-tag" style="background: #21BAEB;">Large Language Model</div>`,
  'Music-Streaming': `<div class="work-item-tag" style="background: #21BAEB;">Music-Streaming</div>`,
  TailwindCSS: `<div class="work-item-tag" style="background: #CA49F8;">TailwindCSS</div>`,
  Firebase: `<div class="work-item-tag" style="background: #CA49F8;">Firebase</div>`,
  'AI-Agent': `<div class="work-item-tag" style="background: #CA49F8;">AI-Agent</div>`,
  Blockchain: `<div class="work-item-tag" style="background: #DA3908;">Blockchain</div>`,
  Prisma: `<div class="work-item-tag" style="background: #DA3908;">Prisma</div>`,
  Clerk: `<div class="work-item-tag" style="background: #DA3908;">Clerk</div>`,
  Laravel: `<div class="work-item-tag" style="background: #AA3058;">Laravel</div>`,
  TypeScript: `<div class="work-item-tag" style="background: #AA3058;">TypeScript</div>`,
  Convex: `<div class="work-item-tag" style="background: #AA3058;">Convex</div>`,
};
